# Generated by Django 3.1.7 on 2021-03-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Task Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(max_length=200, verbose_name='Task description')),
                ('deadline_date', models.DateTimeField(verbose_name='Deadline')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('status', models.CharField(choices=[('done', 'Done'), ('undone', 'UnDone')], default='undone', max_length=10, verbose_name='Task Status')),
                ('reminder', models.SmallIntegerField(choices=[(1, 'one day earlier'), (2, 'two days earlier'), (3, 'three days earlier'), (7, 'a weak earlier'), (30, 'a month earlier')])),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'db_table': 'task',
                'ordering': ('-deadline_date',),
            },
        ),
    ]
